#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

sudo: required
dist: trusty

os:
  - linux
  - osx
  
# Only use continuous integration on the master branch
branches: 
    only: 
        - master

# Send notifications on every build failure to comitter and author. Never send
# notifications for sucessful builds.
notifications:
    email:
        on_success: never

# We're not really using C (but Red and Rebol, of course), but setting language
# to C disables Travis CI's Ruby-specific defaults.
language: c

env:
    global:
         #
         # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
         #
         - secure: "Bex3tqrlsnv+t3+AJu6nG8bcbfHXeBNWIUUdcEeyB8gWnWnVuBsC5hTw9cUhEWJchJSsV4LeWVL51harzOQRntszyfjeNvPQozCXbTQVGd1tn5Rpt1QKN9VBK007c+ERj9L8JzFkM2HdeVusYY4Bz5tI883DSJkydyJpJp21mG9i8a17bqJsgBW0JmMsMsdv1ilaeb8/Luo8bn0ObIWTTz+4/6RF4XU9UcWLH7I4HlGb3qufR9chWCX7jTT0SLRkEgfudr+KVrY4xIspiPlVwrKvagnOTFcYLxN4JpGOgn1rnCcOxsWo4kE4dwgXZvEn8W2HJmJhzhAHDLkF0S7YhIDQaScJLwSVECI9xu68V5siWdyhzyrSb2K7V8Mtzryjzq1QueCrRRTj7XLY7sx5OxeP//RVMY0Poil5DdB84nI1wezzmT1kj7dkc1Fr1ZqdYSEfCZNd1v+DeRmAf/N70xUyx1tSxAHD96kjDM3lGILIrlt9RLWdeT0BqxQxzaKCowPVgfztH0nzPcoe1DfNfIhG9mEdjeJfLC7hAgc9Dn0KTo/oSwX/TBsTavV+6SPxH1D4q1xVdY9p4G2hS/N1xaqf7ys4DQOPwWZwvhujwGtto4fy7VMvDtX7jI6++0dJe+baG0DetlHvUGKzWpBJgk02k3mREH+9Ui8f7T9vn8Y="
         
         # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
         #
         - secure: "IlBRG9mRM0BDtb9ZJDKl4QVRjs/e3KxvjEdVS9e8+PlGq+xMDVGQdje9WOED/bhTcoAYabhLKkXY8YZg6rlVj4ecyjjmZRfPA4D9YVMVHZVNldLX9Ed79Kv95dTvFdn6xl9Tbk/CEqtxfDwcN2hZqv9M3TXN2+sKzny6p4ENc8O7sz0Stb4GyFgPdWSIs4SZv/r8/feMgWiUx+q1NFFarMmFsLtKVuiPIyoU6fGW1zZPyh10jKuhi9GYBStcMHIWqvU+9+jbqchMJT1t/1fyEf0fJokNMH2KXCVDbsu7nKhaVZbIxirLdZNicKfzype1uRgzAB/Crpup+TwnINd17HPSqjCnqntuS+pO0mIRcXVhNSE8TG9S8x4N0pgtKYHKyfAjElmjLwPfoMhu5VlZishn6heeUALbQ7y44YwWwG8EoW4PnRFIGg7V4EjlHJkcmDhJWrZX2hVvSGJ72lFhHXFMcr+VKhXWlmK97XdFAz/c/LlSyyrmKtIE6W5kwhJC8bbrpETA/wQ9pP3WEVY28bka24LqI1g0hiDn7cyXae7Ikss36Y8eB/9/00EovCPHw1o+dyenXI10Q8+yorQ42xrjo1bXuYRohCvI+FmV4XFLkJ+c6wDTSKhJTcUhZsQva2F0ipeyqhGQQGkLiZ8BvdoSPHHBx2odikgho9VQZ48="
 
         - AWS_S3_BUCKET_NAME: "metaeducation"


# We run the Red and Red/System test suites separately, to don't run against
# Travis CI's current 50 minute execution time limitation.
env:
    - TEST_SUITE=tests
    - TEST_SUITE=system/tests

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi

install:
    # 32b "multiarch" libraries are necessary to run 32b binaries on the 64b
    # Travis VM.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libc6:i386 libcurl3:i386; fi
    # Rebol 2 is necessary for building Red.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://static.red-lang.org/tmp/rebol; chmod +x rebol; sudo mv ./rebol /usr/local/bin/rebol2; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://static.red-lang.org/tmp/rebol-osx; chmod +x rebol-osx; sudo mv ./rebol-osx /usr/local/bin/rebol2; fi

script:
    - rebol2 -qws ${TEST_SUITE}/run-all.r --batch

# notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/f9318a4a24c9157f20d1
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_NAME
    skip_cleanup: true
    upload-dir: travis-builds
