#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

sudo: required
dist: trusty

os:
  - linux
  - osx
  
# Only use continuous integration on the master branch
branches: 
    only: 
        - master

# Send notifications on every build failure to comitter and author. Never send
# notifications for sucessful builds.
notifications:
    email:
        on_success: never

# We're not really using C (but Red and Rebol, of course), but setting language
# to C disables Travis CI's Ruby-specific defaults.
language: c

env:
    global:
         #
         # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
         #
         - secure: "KEkzi2T3inudSCbj2+qfu3uuwP7JSWW1qtnFHGi4pKDQUR/B2IeYdQf15Rl0/bCp7AwAD06ZwqgZf0QaU+5Ubh1mB/TbEDR9AGR+12z9JGlFN04DUe4w4R1AVgCQhXylgFz0DGMWaEFej0iRZjGxUw8fPw1oMRZKei/fMN78dXXszJERRdG72Ukf/tWFNM3HIdF44ACdP5ZR2Ra/nWV4bfMqfC8AUKxAjRYAp8c3AaZ5dNJBVR1izrhmeA9mciBB60DRs9VD35Iit8yuMlLYwtlNVScHaqaUjcuwmz9lOZ2TzVBhbMBabpDXpnrnhibrvSNC/m13atSJCsh+qWrazXAhz+ck0O4Kt5cPBoaqt0Hsfgf2D4R8oKB/3djEaIoMp69hnXIQfHF/7t+cGXG25ewxx56U0CFboQfbwMOs8Xhdv5MCF1GDVQNmg991GjGPLfbUTewJQgnj+HAQyw84RX6IbC7ASe+oxezkivPYKM3Pui0wkzg374qP/S4oYqIQhppZnVbhws9FANQBbaTQVw9tMi90DCmvZJwjTApq6mK44AzKVAKW2+Vn+5QY+WqvhaQJpMunjfhqJ/woxVJGi5mTW4FysPMQrTX4tY3iuRaHL2bSsRXG8qDtqV4yn9chv+M+32Zu+Nf7TrjK479HdG5ptbCVJh7L6jKt8krVjQ=="
         
         # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
         #
         - secure: "sJFdLdb5mv955Rp/AWiI6N+L6lbWAZn3MzsDc7nRRMjVtTuDb/mjqL2Bb51Pv0PWIdbPYUtub8DZQeRPBkAQQ+ZX6AeJkZdIDnVrgcSyMpxMLQVRiX2NSMXgwIk8SK2Nfq5Lr+1nIHoxXvMiz54EuTCx1rQpkaHYBUWgWPb9XeqUm8+sA2bC+m7p/nsaDlenBTllxVXpcdFyPHY6sLzcx04AFQLTZ/xtxiGX4VxyZaeSwf00F9UVT3kTd3a7L64YfvejI3xTUhxh0loKkcuXgU+4PgvCIwr/ddZCLnwkPgCMv08CRVFGM6GaDTRM0wFjDVZmZMDDqPmlJH3Qb1JJO3Y/KcaEZkI0ZoQ7nEEHowaV/N4jlq710ozOO0xJkXlWRvaMFillkfdt4jqiBgwJNHx4hKEUHHkN17kXRatNTAxt7K8xMKQingPwLO63TBeCG9CravIqCqbDk2Jg9ZaqZ7XnlqZK50gyUzbwcpndP40rbqbDvtIzMF/BADTN5++kJLJZg4o9lkivPVdsQlJPGKaE6KBQIhd+dd8w8VWK5qS4F9zw1k6YFYcfBhquDaiSQKORtYBBRyhsD6roA5lyhf+OnEjfSDwLU6TSjRkj/vRI+TTv+3rs60zj1CI0h+ap3kAxmWgj2g7F//wK2tezkukyhKQMGekEkiB4hYavO0g="
 
         - AWS_S3_BUCKET_NAME: "metaeducation"


# We run the Red and Red/System test suites separately, to don't run against
# Travis CI's current 50 minute execution time limitation.
env:
    - TEST_SUITE=tests
    - TEST_SUITE=system/tests

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi

install:
    # 32b "multiarch" libraries are necessary to run 32b binaries on the 64b
    # Travis VM.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libc6:i386 libcurl3:i386; fi
    # Rebol 2 is necessary for building Red.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://static.red-lang.org/tmp/rebol; chmod +x rebol; sudo mv ./rebol /usr/local/bin/rebol2; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://static.red-lang.org/tmp/rebol-osx; chmod +x rebol-osx; sudo mv ./rebol-osx /usr/local/bin/rebol2; fi

script:
    - rebol2 -qws ${TEST_SUITE}/run-all.r --batch

# notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/f9318a4a24c9157f20d1
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_NAME
    skip_cleanup: true
    upload-dir: travis-builds
